In [26]:
import pandas as pd

In [62]:

class TextSimilarityExample:
    def __init__(self, statementls):
        self.statements = statementls

#여러 개의 문서가 statements에 들어가있음.
        
    # TF 계산
    def TF(self, sentence):
        tokens = []
        for statement in self.statements:
            tokens += statement.split()
        wordSet = set(tokens)
        wordDict = dict.fromkeys(wordSet, 0)
        
        for statement in self.statements:
            for word in statement.split():
                wordDict[word] += 1
        self.df = pd.DataFrame([wordDict])
        
        dictionary = {}
        self.bowCount = len(tokens)
        for word, count in wordDict.items():
            dictionary[word] = count/float(self.bowCount)
            
        return dictionary
    
    # IDF 계산
    def IDF(self, statements):
        import math
        idfValues = {}
        N = len(statements)
        
        idfDict = dict.fromkeys(statements[0].keys(), 0)
        for statement in statements:
            for word, val in statement.items():
                if val > 0:
                    idfValues[word] += 1
                    
        for word, val in idfDict.items():
            idfValues[word] = math.log10(N / float(val))
            
        return idfValues
    
    # TF IDF 계산 #query = 0번째 리스트
    def TF_IDF(self, query):
        tf = self.TF(query)
        idfs = self.IDF(query)
        for word, val in tf.items():
            tfidf[word] = val * idfs[word]
        return vectors

    # 벡터 출력
    def displayVectors(self, vectors):
        pass
    # 벡터 정보 출력
    # 유사도 측정
    def cosineSimilarity(vec1):
        pass
    # 코사인 유사도 출력
    # TF-IDF -> 벡터출력 -> 코사인유사도
    def demo(self):
        inputQuery = self.statements[0] #리스트 여러 개 중 첫번째를 query에 입력
        vectors = self.TF_IDF(inputQuery) #0번째 리스트가 TF_IDF로 들어감
        
        self.displayVectors(vectors)
        self.cosineSimilarity(vectors[0], vectors[1])

In [63]:
#2개의 문서
statementls = ['ruled india', 'chalukyas ruled Badami', 'I hate banana', 'you love apple']
similarity = TextSimilarityExample(statementls)
similarity.demo()

AttributeError: 'str' object has no attribute 'keys'

# sklearn

In [55]:
from sklearn.feature_extraction.text import TfidfVectorizer
from collections import defaultdict

document_ls = statementls

vectorizer = TfidfVectorizer()


tfidf = vectorizer.fit_transform(document_ls)

word2id = defaultdict(lambda : 0)
for idx, feature in enumerate(vectorizer.get_feature_names()):
    word2id[feature] = idx

In [56]:
import pandas as pd
count_vect_df = pd.DataFrame(tfidf.todense(), columns = vectorizer.get_feature_names())
count_vect_df

,apple,badami,banana,chalukyas,hate,india,love,ruled,you
0,0.00000,0.000000,0.000000,0.000000,0.000000,0.785288,0.00000,0.619130,0.00000
1,0.00000,0.617614,0.000000,0.617614,0.000000,0.000000,0.00000,0.486934,0.00000
2,0.00000,0.000000,0.707107,0.000000,0.707107,0.000000,0.00000,0.000000,0.00000
3,0.57735,0.000000,0.000000,0.000000,0.000000,0.000000,0.57735,0.000000,0.57735