In [1]:
import MySQLdb

In [2]:
db = MySQLdb.connect(host="localhost",  # host      # 127.0.0.1
                     user="root",       # username  # root
                     passwd="1234",     # password  # 1234
                     db="naver_movie")         # DB NAME

In [3]:
db

In [4]:
# 데이터베이스 커서(Cursor)는 일련의 데이터에 
# 순차적으로 액세스할 때 검색 및 "현재 위치"를 
# 포함하는 데이터 요소이다.
cur = db.cursor()
# https://movie.naver.com/movie/bi/mi/basic.nhn?code=161967

In [5]:
# IF(조건, 참값, 거짓값)
query = """
        CREATE TABLE IF NOT EXISTS naver_movie
            (code    INTEGER      NOT NULL      PRIMARY KEY,
             created_at    DATETIME DEFAULT CURRENT_TIMESTAMP,
             title   VARCHAR(100) NOT NULL,
             story   TEXT,
             open_date  DATE)
             ENGINE INNODB;
        """
cur.execute(query)

0

In [7]:
query = """
        CREATE TABLE IF NOT EXISTS movie_comment(
            score    INTEGER    NOT NULL,
            content  TEXT       NOT NULL,
            movie_code INTEGER,
            writer   VARCHAR(100),
            write_date DATETIME,
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (writer, write_date),
            FOREIGN KEY(movie_code)
            REFERENCES naver_movie(code) on delete cascade)
            ENGINE INNODB;
"""
cur.execute(query)

0

## 영화 크롤링

In [27]:
import requests
from bs4 import BeautifulSoup
from urllib import parse

In [28]:
MOVIE_LIST_URL = 'https://movie.naver.com/movie/sdb/rank/rmovie.nhn'

# ?sel=pnt&date=20190616

In [35]:
def get_movie_list(start_page=1, end_page=1):
    URL = "https://movie.naver.com/movie/sdb/rank/rmovie.nhn"
    params = {
        'sel':'pnt',
        'date':20190616
    }
    
    movie_list = []
    for i in range(start_page, end_page+1):
        params['page'] = i
        
        resp = requests.get(URL, params)
        soup = BeautifulSoup(resp.content)
        
        list_ranking = soup.find(class_='list_ranking').find_all('tr')
        for movie_tr in list_ranking:
            try:
                code = movie_tr.find('a')['href'].split('=')[-1]
                title = movie_tr.find('a').text
            
                movie_list.append({
                    'code':code,
                    'title':title
                })
            except Exception:
                pass
            
    return movie_list

In [36]:
def get_movie_info(movie):
    code = movie.get('code')
    title = movie.get('title')
    
    base_url = 'https://movie.naver.com/movie/bi/mi/basic.nhn'
    params = {
        'code': code,
    }
    
    resp = requests.get(base_url, params)
    soup = BeautifulSoup(resp.content)
    
    open_date_tag = soup.find('dl', class_='info_spec').find('dd').find_all('span')[-1]

    open_date = open_date_tag.text
    story = soup.find('div', class_='story_area')
    
    movie['story'] = story
    movie['open_date'] = open_date
    
    return movie

In [37]:
movie_list = get_movie_list()
movie_list[0]

{'code': '171539', 'title': '그린 북'}

In [ ]:
get_movie_info(movie_list[0])

In [ ]:
def

In [ ]:
# https://movie.naver.com/movie/sdb/rank/rmovie.nhn?sel=pnt&date=20190616

In [8]:
import requests
from urllib import parse
from bs4 import BeautifulSoup
import datetime
import math

In [10]:
# movie_list

# 한 화면에 50페이지
PAGE_SIZE = 50
MOVIE_LENGTH = 100
pages = math.ceil(MOVIE_LENGTH/PAGE_SIZE)
pages

2

In [11]:
def get_movie_list(start_page, end_page):
    today = datetime.datetime.now()
    
    movie_list = []
    for page in range(start_page, end_page+1):
        movie_list_url = 'https://movie.naver.com/movie/sdb/rank/rmovie.nhn'
        params = {
            'sel':'pnt',
            'date':today.strftime('%Y%m%d'),
            'page':page
        }
        resp = requests.get(movie_list_url)
        resp.encoding = 'utf-8'
    
        soup = BeautifulSoup(resp.content)
        # list_ranking = soup.find(class_='list_ranking').find_all('tr')
        list_ranking = soup.select('.list_ranking>tbody>tr')
    
        for movie_tr in list_ranking:
            all_td = movie_tr.find_all('td')
            try:
                rank = all_td[0].img['alt']
                link = all_td[1].find('a')['href']
                title = all_td[1].find('a').text
                
                code = parse.parse_qs(parse.urlsplit(link).query)['code'][0]
            except TypeError:
                pass

            else:
                movie_list.append({
                    'img':img,
                    'link':link,
                    'title':title,
                    'code':code
                })
                
    return movie_list

In [12]:
def get_movie_detail(code):
    base_url = 'https://movie.naver.com/movie/bi/mi/basic.nhn'
    params = {
        'code':code
    }
    resp = requests.get(base_url, params)
    resp.encoding ='utf-8'
    soup = BeautifulSoup(resp.content)
    
    opend = soup.find('dt', text='개요()').find_next_sibling('dd').find_all('span')[-1].text.strip()
    opend = ''.join(opend.split('\n'))[:10]

    story = soup.find('div', class_='story_area')
    print(story)
    return {
        'opend':opend,
        'story':story
    }
    
    
def get_movie_comment(code, last_comment='15788558'):
    base_url = '/movie/bi/mi/pointWriteFormList.nhn'
    page = 1
    comment_list = []
    
    while True:
        params={
            'code':171539,
            'type':'after',
            'order':'newest',
            'page':page
        }
        resp = requests.get(base_url, params)
        resp.encoding = 'utf-8'
        soup = BeautifulSoup(resp.content)
        
        comments = soup.find('div', class_='score_result').find_all('li')
        for comment in comments:
            star = comment.find('div', class_='star_score').text
            reple = comment.find('div', class_='score_reple').find('p').text
            
            dd = comment.find('div', class_='score_reple').find('dl').find_all('dd')
            user = dd[0]
            created_at = dd[1]
            
            comment_id = comment.find('div', class_='btn_area').find_all('span')[-1]['class'][0].split('_')[1]
            
            if int(comment_id) <= int(last_comment):
                return comment_list
            
            # 실습용 코드
            if page ==3:
                break
            
            comment_list.append({
                'star':star,
                'reple':reple,
                'user': user,
                'created_at': created_at,
                'comment_id': comment_id
            })
            
        
        page += 1
    return comment_list

In [13]:
movie_list = get_movie_list(1, pages)

In [16]:
movie_list

[{'img': '01',
  'link': '/movie/bi/mi/basic.nhn?code=161967',
  'title': '기생충',
  'code': '161967'},
 {'img': '02',
  'link': '/movie/bi/mi/basic.nhn?code=163788',
  'title': '알라딘',
  'code': '163788'},
 {'img': '03',
  'link': '/movie/bi/mi/basic.nhn?code=97631',
  'title': '맨 인 블랙: 인터내셔널',
  'code': '97631'},
 {'img': '04',
  'link': '/movie/bi/mi/basic.nhn?code=164125',
  'title': '엑스맨: 다크 피닉스',
  'code': '164125'},
 {'img': '05',
  'link': '/movie/bi/mi/basic.nhn?code=177371',
  'title': '0.0MHz',
  'code': '177371'},
 {'img': '06',
  'link': '/movie/bi/mi/basic.nhn?code=181704',
  'title': '로켓맨',
  'code': '181704'},
 {'img': '07',
  'link': '/movie/bi/mi/basic.nhn?code=18781',
  'title': '이웃집 토토로',
  'code': '18781'},
 {'img': '08',
  'link': '/movie/bi/mi/basic.nhn?code=136900',
  'title': '어벤져스: 엔드게임',
  'code': '136900'},
 {'img': '09',
  'link': '/movie/bi/mi/basic.nhn?code=183836',
  'title': '천로역정: 천국을 찾아서',
  'code': '183836'},
 {'img': '010',
  'link': '/movie/bi/mi/basic.nhn?code=177967',
  'title': '악인전',
  'code': '177967'},
 {'img': '11',
  'link': '/movie/bi/mi/basic.nhn?code=179125',
  'title': '롱 리브 더 킹: 목포 영웅',
  'code': '179125'},
 {'img': '12',
  'link': '/movie/bi/mi/basic.nhn?code=180169',
  'title': '어린 의뢰인',
  'code': '180169'},
 {'img': '13',
  'link': '/movie/bi/mi/basic.nhn?code=167053',
  'title': '업사이드',
  'code': '167053'},
 {'img': '14',
  'link': '/movie/bi/mi/basic.nhn?code=101966',
  'title': '토이 스토리 4',
  'code': '101966'},
 {'img': '15',
  'link': '/movie/bi/mi/basic.nhn?code=137865',
  'title': '세상을 바꾼 변호인',
  'code': '137865'},
 {'img': '16',
  'link': '/movie/bi/mi/basic.nhn?code=183132',
  'title': '교회오빠',
  'code': '183132'},
 {'img': '17',
  'link': '/movie/bi/mi/basic.nhn?code=174065',
  'title': '걸캅스',
  'code': '174065'},
 {'img': '18',
  'link': '/movie/bi/mi/basic.nhn?code=139673',
  'title': '여교사',
  'code': '139673'},
 {'img': '19',
  'link': '/movie/bi/mi/basic.nhn?code=97672',
  'title': '노리개: 그녀의 눈물',
  'code': '97672'},
 {'img': '20',
  'link': '/movie/bi/mi/basic.nhn?code=137327',
  'title': '고질라: 킹 오브 몬스터',
  'code': '137327'},
 {'img': '21',
  'link': '/movie/bi/mi/basic.nhn?code=181698',
  'title': '존 윅 3: 파라벨룸',
  'code': '181698'},
 {'img': '22',
  'link': '/movie/bi/mi/basic.nhn?code=173123',
  'title': '스파이더맨: 파 프롬 홈',
  'code': '173123'},
 {'img': '23',
  'link': '/movie/bi/mi/basic.nhn?code=165022',
  'title': '호텔 뭄바이',
  'code': '165022'},
 {'img': '24',
  'link': '/movie/bi/mi/basic.nhn?code=159366',
  'title': '호랑이보다 무서운 겨울손님',
  'code': '159366'},
 {'img': '25',
  'link': '/movie/bi/mi/basic.nhn?code=183850',
  'title': '애나벨 집으로',
  'code': '183850'},
 {'img': '26',
  'link': '/movie/bi/mi/basic.nhn?code=180209',
  'title': '기방도령',
  'code': '180209'},
 {'img': '27',
  'link': '/movie/bi/mi/basic.nhn?code=185935',
  'title': '좀비 워',
  'code': '185935'},
 {'img': '28',
  'link': '/movie/bi/mi/basic.nhn?code=175322',
  'title': '마녀',
  'code': '175322'},
 {'img': '29',
  'link': '/movie/bi/mi/basic.nhn?code=162203',
  'title': '폴라로이드',
  'code': '162203'},
 {'img': '30',
  'link': '/movie/bi/mi/basic.nhn?code=183820',
  'title': '사탄의 인형',
  'code': '183820'},
 {'img': '31',
  'link': '/movie/bi/mi/basic.nhn?code=177483',
  'title': '배심원들',
  'code': '177483'},
 {'img': '33',
  'link': '/movie/bi/mi/basic.nhn?code=177508',
  'title': '강변호텔',
  'code': '177508'},
 {'img': '34',
  'link': '/movie/bi/mi/basic.nhn?code=179875',
  'title': '비스트',
  'code': '179875'},
 {'img': '35',
  'link': '/movie/bi/mi/basic.nhn?code=152471',
  'title': '미친사랑',
  'code': '152471'},
 {'img': '36',
  'link': '/movie/bi/mi/basic.nhn?code=183113',
  'title': '극장판 오소마츠 6쌍둥이',
  'code': '183113'},
 {'img': '37',
  'link': '/movie/bi/mi/basic.nhn?code=167633',
  'title': '마담 싸이코',
  'code': '167633'},
 {'img': '38',
  'link': '/movie/bi/mi/basic.nhn?code=173668',
  'title': '나랏말싸미',
  'code': '173668'},
 {'img': '39',
  'link': '/movie/bi/mi/basic.nhn?code=69598',
  'title': '체 게바라: 1부 아르헨티나',
  'code': '69598'},
 {'img': '40',
  'link': '/movie/bi/mi/basic.nhn?code=183782',
  'title': '독고다이',
  'code': '183782'},
 {'img': '41',
  'link': '/movie/bi/mi/basic.nhn?code=184975',
  'title': '블랙 스완: 흑화',
  'code': '184975'},
 {'img': '42',
  'link': '/movie/bi/mi/basic.nhn?code=184977',
  'title': '아나운서 살인사건',
  'code': '184977'},
 {'img': '43',
  'link': '/movie/bi/mi/basic.nhn?code=184974',
  'title': '파라노말 액티비티: 드림 하우스',
  'code': '184974'},
 {'img': '44',
  'link': '/movie/bi/mi/basic.nhn?code=151550',
  'title': '서스페리아',
  'code': '151550'},
 {'img': '45',
  'link': '/movie/bi/mi/basic.nhn?code=164907',
  'title': '레드슈즈',
  'code': '164907'},
 {'img': '46',
  'link': '/movie/bi/mi/basic.nhn?code=182045',
  'title': '나의 마더',
  'code': '182045'},
 {'img': '47',
  'link': '/movie/bi/mi/basic.nhn?code=178544',
  'title': '사자',
  'code': '178544'},
 {'img': '48',
  'link': '/movie/bi/mi/basic.nhn?code=159743',
  'title': '평일 오후 3시의 연인',
  'code': '159743'},
 {'img': '49',
  'link': '/movie/bi/mi/basic.nhn?code=185045',
  'title': '엘리펀트킹 덤보',
  'code': '185045'},
 {'img': '50',
  'link': '/movie/bi/mi/basic.nhn?code=183870',
  'title': '빅샤크2: 해저2만리',
  'code': '183870'},
 {'img': '01',
  'link': '/movie/bi/mi/basic.nhn?code=161967',
  'title': '기생충',
  'code': '161967'},
 {'img': '02',
  'link': '/movie/bi/mi/basic.nhn?code=163788',
  'title': '알라딘',
  'code': '163788'},
 {'img': '03',
  'link': '/movie/bi/mi/basic.nhn?code=97631',
  'title': '맨 인 블랙: 인터내셔널',
  'code': '97631'},
 {'img': '04',
  'link': '/movie/bi/mi/basic.nhn?code=164125',
  'title': '엑스맨: 다크 피닉스',
  'code': '164125'},
 {'img': '05',
  'link': '/movie/bi/mi/basic.nhn?code=177371',
  'title': '0.0MHz',
  'code': '177371'},
 {'img': '06',
  'link': '/movie/bi/mi/basic.nhn?code=181704',
  'title': '로켓맨',
  'code': '181704'},
 {'img': '07',
  'link': '/movie/bi/mi/basic.nhn?code=18781',
  'title': '이웃집 토토로',
  'code': '18781'},
 {'img': '08',
  'link': '/movie/bi/mi/basic.nhn?code=136900',
  'title': '어벤져스: 엔드게임',
  'code': '136900'},
 {'img': '09',
  'link': '/movie/bi/mi/basic.nhn?code=183836',
  'title': '천로역정: 천국을 찾아서',
  'code': '183836'},
 {'img': '010',
  'link': '/movie/bi/mi/basic.nhn?code=177967',
  'title': '악인전',
  'code': '177967'},
 {'img': '11',
  'link': '/movie/bi/mi/basic.nhn?code=179125',
  'title': '롱 리브 더 킹: 목포 영웅',
  'code': '179125'},
 {'img': '12',
  'link': '/movie/bi/mi/basic.nhn?code=180169',
  'title': '어린 의뢰인',
  'code': '180169'},
 {'img': '13',
  'link': '/movie/bi/mi/basic.nhn?code=167053',
  'title': '업사이드',
  'code': '167053'},
 {'img': '14',
  'link': '/movie/bi/mi/basic.nhn?code=101966',
  'title': '토이 스토리 4',
  'code': '101966'},
 {'img': '15',
  'link': '/movie/bi/mi/basic.nhn?code=137865',
  'title': '세상을 바꾼 변호인',
  'code': '137865'},
 {'img': '16',
  'link': '/movie/bi/mi/basic.nhn?code=183132',
  'title': '교회오빠',
  'code': '183132'},
 {'img': '17',
  'link': '/movie/bi/mi/basic.nhn?code=174065',
  'title': '걸캅스',
  'code': '174065'},
 {'img': '18',
  'link': '/movie/bi/mi/basic.nhn?code=139673',
  'title': '여교사',
  'code': '139673'},
 {'img': '19',
  'link': '/movie/bi/mi/basic.nhn?code=97672',
  'title': '노리개: 그녀의 눈물',
  'code': '97672'},
 {'img': '20',
  'link': '/movie/bi/mi/basic.nhn?code=137327',
  'title': '고질라: 킹 오브 몬스터',
  'code': '137327'},
 {'img': '21',
  'link': '/movie/bi/mi/basic.nhn?code=181698',
  'title': '존 윅 3: 파라벨룸',
  'code': '181698'},
 {'img': '22',
  'link': '/movie/bi/mi/basic.nhn?code=173123',
  'title': '스파이더맨: 파 프롬 홈',
  'code': '173123'},
 {'img': '23',
  'link': '/movie/bi/mi/basic.nhn?code=165022',
  'title': '호텔 뭄바이',
  'code': '165022'},
 {'img': '24',
  'link': '/movie/bi/mi/basic.nhn?code=159366',
  'title': '호랑이보다 무서운 겨울손님',
  'code': '159366'},
 {'img': '25',
  'link': '/movie/bi/mi/basic.nhn?code=183850',
  'title': '애나벨 집으로',
  'code': '183850'},
 {'img': '26',
  'link': '/movie/bi/mi/basic.nhn?code=180209',
  'title': '기방도령',
  'code': '180209'},
 {'img': '27',
  'link': '/movie/bi/mi/basic.nhn?code=185935',
  'title': '좀비 워',
  'code': '185935'},
 {'img': '28',
  'link': '/movie/bi/mi/basic.nhn?code=175322',
  'title': '마녀',
  'code': '175322'},
 {'img': '29',
  'link': '/movie/bi/mi/basic.nhn?code=162203',
  'title': '폴라로이드',
  'code': '162203'},
 {'img': '30',
  'link': '/movie/bi/mi/basic.nhn?code=183820',
  'title': '사탄의 인형',
  'code': '183820'},
 {'img': '31',
  'link': '/movie/bi/mi/basic.nhn?code=177483',
  'title': '배심원들',
  'code': '177483'},
 {'img': '33',
  'link': '/movie/bi/mi/basic.nhn?code=177508',
  'title': '강변호텔',
  'code': '177508'},
 {'img': '34',
  'link': '/movie/bi/mi/basic.nhn?code=179875',
  'title': '비스트',
  'code': '179875'},
 {'img': '35',
  'link': '/movie/bi/mi/basic.nhn?code=152471',
  'title': '미친사랑',
  'code': '152471'},
 {'img': '36',
  'link': '/movie/bi/mi/basic.nhn?code=183113',
  'title': '극장판 오소마츠 6쌍둥이',
  'code': '183113'},
 {'img': '37',
  'link': '/movie/bi/mi/basic.nhn?code=167633',
  'title': '마담 싸이코',
  'code': '167633'},
 {'img': '38',
  'link': '/movie/bi/mi/basic.nhn?code=173668',
  'title': '나랏말싸미',
  'code': '173668'},
 {'img': '39',
  'link': '/movie/bi/mi/basic.nhn?code=69598',
  'title': '체 게바라: 1부 아르헨티나',
  'code': '69598'},
 {'img': '40',
  'link': '/movie/bi/mi/basic.nhn?code=183782',
  'title': '독고다이',
  'code': '183782'},
 {'img': '41',
  'link': '/movie/bi/mi/basic.nhn?code=184975',
  'title': '블랙 스완: 흑화',
  'code': '184975'},
 {'img': '42',
  'link': '/movie/bi/mi/basic.nhn?code=184977',
  'title': '아나운서 살인사건',
  'code': '184977'},
 {'img': '43',
  'link': '/movie/bi/mi/basic.nhn?code=184974',
  'title': '파라노말 액티비티: 드림 하우스',
  'code': '184974'},
 {'img': '44',
  'link': '/movie/bi/mi/basic.nhn?code=151550',
  'title': '서스페리아',
  'code': '151550'},
 {'img': '45',
  'link': '/movie/bi/mi/basic.nhn?code=164907',
  'title': '레드슈즈',
  'code': '164907'},
 {'img': '46',
  'link': '/movie/bi/mi/basic.nhn?code=182045',
  'title': '나의 마더',
  'code': '182045'},
 {'img': '47',
  'link': '/movie/bi/mi/basic.nhn?code=178544',
  'title': '사자',
  'code': '178544'},
 {'img': '48',
  'link': '/movie/bi/mi/basic.nhn?code=159743',
  'title': '평일 오후 3시의 연인',
  'code': '159743'},
 {'img': '49',
  'link': '/movie/bi/mi/basic.nhn?code=185045',
  'title': '엘리펀트킹 덤보',
  'code': '185045'},
 {'img': '50',
  'link': '/movie/bi/mi/basic.nhn?code=183870',
  'title': '빅샤크2: 해저2만리',
  'code': '183870'}]

In [24]:
def insert_movie(movie):
    code = movie.get('code')
    title = movie.get('title')
    open_date = movie.get('open_date')
    
    query = """
    INSERT INTO naver_movie
    (code, title, open_date)
    VALUES('{}', '{}', '{}')
    """.format(code, title, open_date)
    
    cur.execute(query)
    
def insert_comment(movie_code, comment):
    # movie_comment

    write = comment.get('writer')
    score = comment.get('score')
    wrter = comment.get('writer')
    write_date = comment.get('write_date')
    content = comment.get('content')
    
    query = """
    INSERT INTO movie_comment
    (score, content, writer, write_date, movie_code)
    VALUES('{}', '{}', '{}')
    """.format(score, content, writer, write_date, movie_code)
    
    cur.execute(query)

In [25]:
insert_movie({
    'code': '12',
    'title': 'ddd',
    'open_date': '2011.01.12',
})

OperationalError: (1054, "Unknown column 'open_date' in 'field list'")

In [ ]:
for movie in movie_list:
    detail = get_movie_detail(movie['code'])
    
    open_date = detail['opend']
    story = detail['story']
    comment_list = get_movie_comment(movie['code'])

In [18]:
resp = requests.get(movie_list_url)
resp

NameError: name 'movie_list_url' is not defined

In [ ]:
# INSERT INTO table (column_list)
# VALUES (value_list)
# ON DUPLICATE KEY UPDATE
#    c1 = v1, 
#    c2 = v2,
#    ...;

In [26]:
cur.close()