In [6]:
import os
import pandas as pd
import xlrd
from datetime import timedelta, date 
import datetime

In [7]:
BASE_DIR = os.getcwd()   #현재 경로 탐색
DATASET_PATH = os.path.join(BASE_DIR, "call.xlsx")   #path 연결
df = pd.read_excel('call.xlsx',index_col='date')   #xlsx파일 DataFrame으로 변환

In [8]:
df.index = pd.to_datetime(df.index)   # index type -> datetime타입으로 변경
df['updown'] = None   #'updown'칼럼 추가

In [10]:
i = 0
for day in df.index:
    ago = day - pd.DateOffset(months=1)
    
    while ago not in df.index:
        ago = ago - timedelta(1)
        
    if df.loc[day]['price'] < df.loc[ago]['price']:
        df['updown'][i] = '하락'
    elif df.loc[day]['price'] == df.loc[ago]['price']:
        df['updown'][i] = 0
    else:
        df['updown'][i] = '상승'
        
    i += 1
    if i % 10 == 0:
        print(i,"번째 입니다")
        
    if datetime.date(2005,1,3) == day.date():
        break

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()

10 번째 입니다

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]

20 번째 입니다
30 번째 입니다
40 번째 입니다
50 번째 입니다
60 번째 입니다
70 번째 입니다
80 번째 입니다
90 번째 입니다
100 번째 입니다
110 번째 입니다
120 번째 입니다
130 번째 입니다
140 번째 입니다
150 번째 입니다
160 번째 입니다
170 번째 입니다
180 번째 입니다
190 번째 입니다
200 번째 입니다
210 번째 입니다
220 번째 입니다
230 번째 입니다
240 번째 입니다
250 번째 입니다
260 번째 입니다
270 번째 입니다
280 번째 입니다
290 번째 입니다
300 번째 입니다
310 번째 입니다
320 번째 입니다
330 번째 입니다
340 번째 입니다
350 번째 입니다
360 번째 입니다
370 번째 입니다
380 번째 입니다
390 번째 입니다
400 번째 입니다
410 번째 입니다
420 번째 입니다
430 번째 입니다
440 번째 입니다
450 번째 입니다
460 번째 입니다
470 번째 입니다
480 번째 입니다
490 번째 입니다
500 번째 입니다
510 번째 입니다
520 번째 입니다
530 번째 입니다
540 번째 입니다
550 번째 입니다
560 번째 입니다
570 번째 입니다
580 번째 입니다
590 번째 입니다
600 번째 입니다
610 번째 입니다
620 번째 입니다
630 번째 입니다
640 번째 입니다
650 번째 입니다
660 번째 입니다
670 번째 입니다
680 번째 입니다
690 번째 입니다
700 번째 입니다
710 번째 입니다
720 번째 입니다
730 번째 입니다
740 번째 입니다
750 번째 입니다
760 번째 입니다
770 번째 입니다
780 번째 입니다
790 번째 입니다
800 번째 입니다
810 번째 입니다
820 번째 입니다
830 번째 입니다
840 번째 입니다
850 번째 입니다
860 번째 입니다
870 번째 입니다
880 번째 입니다
890 번째 입니다
900 번째 입니다
910 번째 입니다
920 번째 입니다
930 번째 입니다
940 번째 입니다
950 번째 입니다
960 번째 입니다
970 번째 입니다
980 번째 입니다
990 번째 입니다
1000 번째 입니다
1010 번째 입니다
1020 번째 입니다
1030 번째 입니다
1040 번째 입니다
1050 번째 입니다
1060 번째 입니다
1070 번째 입니다
1080 번째 입니다
1090 번째 입니다
1100 번째 입니다
1110 번째 입니다
1120 번째 입니다
1130 번째 입니다
1140 번째 입니다
1150 번째 입니다
1160 번째 입니다
1170 번째 입니다
1180 번째 입니다
1190 번째 입니다
1200 번째 입니다
1210 번째 입니다
1220 번째 입니다
1230 번째 입니다
1240 번째 입니다
1250 번째 입니다
1260 번째 입니다
1270 번째 입니다
1280 번째 입니다
1290 번째 입니다
1300 번째 입니다
1310 번째 입니다
1320 번째 입니다
1330 번째 입니다
1340 번째 입니다
1350 번째 입니다
1360 번째 입니다
1370 번째 입니다
1380 번째 입니다
1390 번째 입니다
1400 번째 입니다
1410 번째 입니다
1420 번째 입니다
1430 번째 입니다
1440 번째 입니다
1450 번째 입니다
1460 번째 입니다
1470 번째 입니다
1480 번째 입니다
1490 번째 입니다
1500 번째 입니다
1510 번째 입니다
1520 번째 입니다
1530 번째 입니다
1540 번째 입니다
1550 번째 입니다
1560 번째 입니다
1570 번째 입니다
1580 번째 입니다
1590 번째 입니다
1600 번째 입니다
1610 번째 입니다
1620 번째 입니다
1630 번째 입니다
1640 번째 입니다
1650 번째 입니다
1660 번째 입니다
1670 번째 입니다
1680 번째 입니다
1690 번째 입니다
1700 번째 입니다
1710 번째 입니다
1720 번째 입니다
1730 번째 입니다
1740 번째 입니다
1750 번째 입니다
1760 번째 입니다
1770 번째 입니다
1780 번째 입니다
1790 번째 입니다
1800 번째 입니다
1810 번째 입니다
1820 번째 입니다
1830 번째 입니다
1840 번째 입니다
1850 번째 입니다
1860 번째 입니다
1870 번째 입니다
1880 번째 입니다
1890 번째 입니다
1900 번째 입니다
1910 번째 입니다
1920 번째 입니다
1930 번째 입니다
1940 번째 입니다
1950 번째 입니다
1960 번째 입니다
1970 번째 입니다
1980 번째 입니다
1990 번째 입니다
2000 번째 입니다
2010 번째 입니다
2020 번째 입니다
2030 번째 입니다
2040 번째 입니다
2050 번째 입니다
2060 번째 입니다
2070 번째 입니다
2080 번째 입니다
2090 번째 입니다
2100 번째 입니다
2110 번째 입니다
2120 번째 입니다
2130 번째 입니다
2140 번째 입니다
2150 번째 입니다
2160 번째 입니다
2170 번째 입니다
2180 번째 입니다
2190 번째 입니다
2200 번째 입니다
2210 번째 입니다
2220 번째 입니다
2230 번째 입니다
2240 번째 입니다
2250 번째 입니다
2260 번째 입니다
2270 번째 입니다
2280 번째 입니다
2290 번째 입니다
2300 번째 입니다
2310 번째 입니다
2320 번째 입니다
2330 번째 입니다
2340 번째 입니다
2350 번째 입니다
2360 번째 입니다
2370 번째 입니다
2380 번째 입니다
2390 번째 입니다
2400 번째 입니다
2410 번째 입니다
2420 번째 입니다
2430 번째 입니다
2440 번째 입니다
2450 번째 입니다
2460 번째 입니다
2470 번째 입니다
2480 번째 입니다
2490 번째 입니다
2500 번째 입니다
2510 번째 입니다
2520 번째 입니다
2530 번째 입니다
2540 번째 입니다
2550 번째 입니다
2560 번째 입니다
2570 번째 입니다
2580 번째 입니다
2590 번째 입니다
2600 번째 입니다
2610 번째 입니다
2620 번째 입니다
2630 번째 입니다
2640 번째 입니다
2650 번째 입니다
2660 번째 입니다
2670 번째 입니다
2680 번째 입니다
2690 번째 입니다
2700 번째 입니다
2710 번째 입니다
2720 번째 입니다
2730 번째 입니다
2740 번째 입니다
2750 번째 입니다
2760 번째 입니다
2770 번째 입니다
2780 번째 입니다
2790 번째 입니다
2800 번째 입니다
2810 번째 입니다
2820 번째 입니다
2830 번째 입니다
2840 번째 입니다
2850 번째 입니다
2860 번째 입니다
2870 번째 입니다
2880 번째 입니다
2890 번째 입니다
2900 번째 입니다
2910 번째 입니다
2920 번째 입니다
2930 번째 입니다
2940 번째 입니다
2950 번째 입니다
2960 번째 입니다
2970 번째 입니다
2980 번째 입니다
2990 번째 입니다
3000 번째 입니다
3010 번째 입니다
3020 번째 입니다
3030 번째 입니다
3040 번째 입니다
3050 번째 입니다
3060 번째 입니다
3070 번째 입니다
3080 번째 입니다
3090 번째 입니다
3100 번째 입니다
3110 번째 입니다
3120 번째 입니다
3130 번째 입니다
3140 번째 입니다
3150 번째 입니다
3160 번째 입니다
3170 번째 입니다
3180 번째 입니다
3190 번째 입니다
3200 번째 입니다
3210 번째 입니다
3220 번째 입니다
3230 번째 입니다
3240 번째 입니다
3250 번째 입니다
3260 번째 입니다
3270 번째 입니다
3280 번째 입니다
3290 번째 입니다
3300 번째 입니다
3310 번째 입니다
3320 번째 입니다
3330 번째 입니다
3340 번째 입니다
3350 번째 입니다
3360 번째 입니다
3370 번째 입니다
3380 번째 입니다
3390 번째 입니다
3400 번째 입니다
3410 번째 입니다
3420 번째 입니다
3430 번째 입니다
3440 번째 입니다
3450 번째 입니다
3460 번째 입니다
3470 번째 입니다
3480 번째 입니다
3490 번째 입니다
3500 번째 입니다
3510 번째 입니다
3520 번째 입니다
3530 번째 입니다
3540 번째 입니다
3550 번째 입니다
3560 번째 입니다
3570 번째 입니다
3580 번째 입니다
3590 번째 입니다
3600 번째 입니다

In [11]:
df_new = df.loc[:'2005-01-03']

In [12]:
df_new.to_csv("test.csv")

In [13]:
pd.read_csv('test.csv')

            date  price updown
0     2019-07-15   1.73     하락
1     2019-07-12   1.74     하락
2     2019-07-11   1.75      0
3     2019-07-10   1.74     하락
4     2019-07-09   1.69     하락
5     2019-07-08   1.73     하락
6     2019-07-05   1.73      0
7     2019-07-04   1.73     하락
8     2019-07-03   1.73     하락
9     2019-07-02   1.73     하락
10    2019-07-01   1.75     하락
11    2019-06-28   1.83     상승
12    2019-06-27   1.77     상승
13    2019-06-26   1.76     상승
14    2019-06-25   1.75     상승
15    2019-06-24   1.75     상승
16    2019-06-21   1.74     상승
17    2019-06-20   1.75     하락
18    2019-06-19   1.76     상승
19    2019-06-18   1.75     상승
20    2019-06-17   1.76     상승
21    2019-06-14   1.74     상승
22    2019-06-13   1.75      0
23    2019-06-12   1.75     상승
24    2019-06-11   1.75     상승
25    2019-06-10   1.75     상승
26    2019-06-07   1.77     상승
27    2019-06-05   1.73     하락
28    2019-06-04   1.75     상승
29    2019-06-03   1.77     상승
...          ...    ...    ...
3576  2005-02-16   3.26      0
3577  2005-02-15   3.26      0
3578  2005-02-14   3.26      0
3579  2005-02-11   3.27     하락
3580  2005-02-07   3.18     하락
3581  2005-02-04   3.22     하락
3582  2005-02-03   3.26     하락
3583  2005-02-02   3.25     하락
3584  2005-02-01   3.26     하락
3585  2005-01-31   3.26     하락
3586  2005-01-28   3.25     하락
3587  2005-01-27   3.24     하락
3588  2005-01-26   3.26     하락
3589  2005-01-25   3.25     하락
3590  2005-01-24   3.25     하락
3591  2005-01-21   3.19     하락
3592  2005-01-20   3.23     하락
3593  2005-01-19   3.25     하락
3594  2005-01-18   3.25     하락
3595  2005-01-17   3.25     하락
3596  2005-01-14   3.26     하락
3597  2005-01-13   3.28      0
3598  2005-01-12   3.27     하락
3599  2005-01-11   3.28      0
3600  2005-01-10   3.27     하락
3601  2005-01-07   3.22     상승
3602  2005-01-06   3.21     하락
3603  2005-01-05   3.28     상승
3604  2005-01-04   3.27     상승
3605  2005-01-03   3.27     상승

[3606 rows x 3 columns]